### ISSUE TITLE
crash:setRefreshing(boolean)' on a null object reference

### ISSUE THREAD

**Issue by geogie** [HotBitmapGG/bilibili-android-client#16]
10-21 16:32:44.885 28129-28129/com.hotbitmapgg.ohmybilibili E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.hotbitmapgg.ohmybilibili, PID: 28129
                                                                              java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                                  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
                                                                                  at android.os.Handler.handleCallback(Handler.java:815)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                  at android.os.Looper.loop(Looper.java:194)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5550)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
                                                                               Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
                                                                                  at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:192)
                                                                                  at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
                                                                                  at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:204)
                                                                                  at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
                                                                                  at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215)
                                                                                  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                  at android.os.Handler.handleCallback(Handler.java:815) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                                  at android.os.Looper.loop(Looper.java:194) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5550) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750) 
                                                                               Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
                                                                                  at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:192) 
                                                                                  at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120) 
                                                                                  at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:204) 
                                                                                  at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144) 
                                                                                  at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215) 
                                                                                  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
                                                                                  at android.os.Handler.handleCallback(Handler.java:815) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                                  at android.os.Looper.loop(Looper.java:194) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5550) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750) 
                                                                               Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
                                                                                  at android.util.Log.getStackTraceString(Log.java:330)
                                                                                  at com.android.internal.os.RuntimeInit.Clog_e(RuntimeInit.java:59)
                                                                                  at com.android.internal.os.RuntimeInit.access$200(RuntimeInit.java:43)
                                                                                  at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:85)
                                                                                  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                                  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
                                                                                  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:66)
                                                                                  at android.os.Handler.handleCallback(Handler.java:815) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                                  at android.os.Looper.loop(Looper.java:194) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5550) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750) 
                                                                               Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.widget.SwipeRefreshLayout.setRefreshing(boolean)' on a null object reference
                                                                                  at com.hotbitmapgg.ohmybilibili.module.home.discover.AllareasRankFragment.finishTask(AllareasRankFragment.java:107)
                                                                                  at com.hotbitmapgg.ohmybilibili.module.home.discover.AllareasRankFragment.lambda$getAllareasRanks$77(AllareasRankFragment.java:96)
                                                                                  at com.hotbitmapgg.ohmybilibili.module.home.discover.AllareasRankFragment.access$lambda$3(AllareasRankFragment.java:0)
                                                                                  at com.hotbitmapgg.ohmybilibili.module.home.discover.AllareasRankFragment$$Lambda$4.call(Unknown Source)
                                                                                  at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
                                                                                  at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                                                  at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215)
                                                                                  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                  at android.os.Handler.handleCallback(Handler.java:815) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                                  at android.os.Looper.loop(Looper.java:194) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5550) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750) 
                                                                               Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.widget.SwipeRefreshLayout.setRefreshing(boolean)' on a null object reference
                                                                                  at com.hotbitmapgg.ohmybilibili.module.home.discover.AllareasRankFragment.lambda$getAllareasRanks$78(AllareasRankFragment.java:99)
                                                                                  at com.hotbitmapgg.ohmybilibili.module.home.discover.AllareasRankFragment.access$lambda$4(AllareasRankFragment.java:0)
                                                                                  at com.hotbitmapgg.ohmybilibili.module.home.discover.AllareasRankFragment$$Lambda$5.call(Unknown Source)
                                                                                  at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
                                                                                  at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
                                                                                  at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
                                                                                  at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:204)
                                                                                  at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
                                                                                  at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215) 
                                                                                  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
                                                                                  at android.os.Handler.handleCallback(Handler.java:815) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                                  at android.os.Looper.loop(Looper.java:194) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5550) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

**Comment by HotBitmapGG** [comment]
Have Fixed the Bug @geogie
