### ISSUE TITLE
楼主大神，登录之后直接崩溃

### ISSUE THREAD

**Issue by Dreamer206602** [HotBitmapGG/bilibili-android-client#19]
`FATAL EXCEPTION: main
                                                                              Process: com.hotbitmapgg.ohmybilibili, PID: 30444
                                                                              java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                                  at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                  at java.util.ArrayList.get(ArrayList.java:308)
                                                                                  at com.hotbitmapgg.ohmybilibili.adapter.AttentionBangumiAdapter.onBindViewHolder(AttentionBangumiAdapter.java:52)
                                                                                  at com.hotbitmapgg.ohmybilibili.adapter.helper.AbsRecyclerViewAdapter.onBindViewHolder(AbsRecyclerViewAdapter.java:104)
                                                                                  at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5822)
                                                                                  at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5855)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5091)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4967)
                                                                                  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                                  at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:541)
                                                                                  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                                  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                                  at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                                  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
                                                                                  at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2843)
                                                                                  at android.view.View.measure(View.java:18026)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5702)
                                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
                                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
                                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
                                                                                  at android.view.View.measure(View.java:18026)
                                                                                  at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:7871)
                                                                                  at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1440)
                                                                                  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                                  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                                  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
                                                                                  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3124)
                                                                                  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
                                                                                  at android.view.View.layout(View.java:16112)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                                  at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1767)
                                                                                  at android.view.View.layout(View.java:16112)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                                  at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                                                  at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                                  at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1364)
                                                                                  at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:852)
                                                                                  at android.view.View.layout(View.java:16112)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                                  at android.view.View.layout(View.java:16112)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                                  at android.view.View.layout(View.java:16112)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                                  at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1197)
                                                                                  at android.view.View.layout(View.java:16112)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                              	at android.vi
`

**Comment by Dreamer206602** [comment]
貌似是数组越界问题，想研究下你的那个数据展示的布局

**Comment by HotBitmapGG** [comment]
@Dreamer206602   已发现这个问题，改好了，马上提交
