### ISSUE TITLE
点击（分区）下面的任何一个item，也有崩溃的现象

### ISSUE THREAD

**Issue by Dreamer206602** [HotBitmapGG/bilibili-android-client#21]
`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.hotbitmapgg.ohmybilibili, PID: 12667
                                                                              java.lang.IndexOutOfBoundsException: Invalid index 1, size is 0
                                                                                  at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                  at java.util.ArrayList.get(ArrayList.java:308)
                                                                                  at com.hotbitmapgg.ohmybilibili.module.home.region.HomeRegionFragment.-com_hotbitmapgg_ohmybilibili_module_home_region_HomeRegionFragment_lambda$4(HomeRegionFragment.java:97)
                                                                                  at com.hotbitmapgg.ohmybilibili.module.home.region.HomeRegionFragment$-void_initRecyclerView__LambdaImpl0.onItemClick(HomeRegionFragment.java)
                                                                                  at com.hotbitmapgg.ohmybilibili.adapter.helper.AbsRecyclerViewAdapter.-com_hotbitmapgg_ohmybilibili_adapter_helper_AbsRecyclerViewAdapter_lambda$1(AbsRecyclerViewAdapter.java:111)
                                                                                  at com.hotbitmapgg.ohmybilibili.adapter.helper.AbsRecyclerViewAdapter$-void_onBindViewHolder_com_hotbitmapgg_ohmybilibili_adapter_helper_AbsRecyclerViewAdapter$ClickableViewHolder_holder_int_position_LambdaImpl0.onClick(AbsRecyclerViewAdapter.java)
                                                                                  at android.view.View.performClick(View.java:4909)
                                                                                  at android.view.View$PerformClick.run(View.java:20390)
                                                                                  at android.os.Handler.handleCallback(Handler.java:815)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                  at android.os.Looper.loop(Looper.java:194)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5826)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1010)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)`

**Comment by HotBitmapGG** [comment]
@Dreamer206602  感谢帮我找bug啊，确实有这个问题，这个分区的获取分区tid的接口去掉了，直接从本地读取了，改好了 ，一会提交

**Comment by Dreamer206602** [comment]
very good
