### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by Litten1106** [HotBitmapGG/bilibili-android-client#34]
在"发现"页面点击搜索框会崩

Android 4.4 

Htc one e8

```
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                                at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:355)
                                                                                at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:324)
                                                                                at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:285)
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
                                                                                at com.hotbitmapgg.bilibili.base.RxBaseActivity.onCreate(RxBaseActivity.java:38)

```

**Comment by Litten1106** [comment]
亲测在style.xml(v19)中加入
```

   <style name="AppTheme.Search" parent="AppTheme">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="android:windowIsTranslucent">true</item>
        <item name="android:windowTranslucentNavigation">false</item>
    </style>

```

就可以了
